title: BdSL Letter Recognition
description: Classify Bangla Sign Letters Using Deep Learning
about:


  This is a BdSL Letter Classifier using Deep Learning built on top of Pytorch.


  The project was build by [Oishee Bintey Hoque](https://oishee30.github.io/OisheeBinteyHoque/)


  More info and the source code can he found below.

  - [**Video of demo detection**](https://youtu.be/U1d2VqyKLXE)
  - [**Reference of Letters**](https://drive.google.com/file/d/1viV8sFMeuYDNv5OW02ruPMfIR4N7Ijwh/view?usp=sharing)



code: https://github.com/Oishee30/web-bdsl-classifier

sampleImages:
  - name: BdSL
    url: https://drive.google.com/file/d/1viV8sFMeuYDNv5OW02ruPMfIR4N7Ijwh/view?usp=sharing

